### ISSUE TITLE
[Beginner][Document] ffmpeg_CentOS7_config Document Internationalization

### ISSUE THREAD

**Issue by Jimmy385898** [TSGU-OSC/Learn_FFmpeg_the_Hard_Way#16]
All documents of this repo need to be save as English and Chinese just like [README.md](https://github.com/TSGU-OSC/Learn_FFmpeg_the_Hard_Way/blob/master/README.md) and [README_zh.md](https://github.com/TSGU-OSC/Learn_FFmpeg_the_Hard_Way/blob/master/README_zh.md) in this repo root directory.

This issue aims to find contributors to take on the following documentation work.

- [ffmpeg_CentOS7_config](https://github.com/TSGU-OSC/Learn_FFmpeg_the_Hard_Way/blob/master/document/ffmpeg_CentOS7_config/README.md)

**Comment by KAKAOYS** [comment]
I want to solve it, please assign it to me, thanks.

**Comment by RichardTamarisk** [comment]
The file involved in the translation of this issue #16 has been changed: from ffmpeg_CentOS7_config to ffmpeg_linux_config, and the contents of the related README.md file have been slightly changed, are you still willing to work on this issue? @KAKAOYS

**Comment by KAKAOYS** [comment]
> The file involved in the translation of this issue #16 has been changed: from ffmpeg_CentOS7_config to ffmpeg_linux_config, and the contents of the related README.md file have been slightly changed, are you still willing to work on this issue? @KAKAOYS

I think it's an interesting thing, and I'm willing to keep working on this issue.
